### ISSUE TITLE
Health check fails on long bootstrap

### ISSUE THREAD

**Issue by johannrichard** [crazy-max/docker-rrdcached#2]
### Behaviour

When the container (Version 1.7.2.) takes a long time to fix permissions (e.g. when quite a few RRD files are stored on an NFS volume and `chown`/`chmod` take ages to finish), the health check fails before the container has properly started and docker will kill the container.

#### Steps to reproduce this issue

1. Set up the container with a considerably large set of RRD files and "faulty" permissions 
2. Launch the container which starts fixing permissions before it's running the `rrchached`
3. Before the container has fixed all permissions, the health check kicks in and the container is stopped

#### Expected behaviour

> Permissions would get fixed and `rrcached` started properly

#### Actual behaviour

> The container exits before `rrcached` is started properly

### Configuration

* Docker version :Docker version 18.06.2, build 6d37f41
* Platform : Linux/Photon OS 3
* Include all necessary configuration files : 

```
  rrdcached:
    image: crazymax/rrdcached
    environment:
      PUID: '1002'
      PGID: '1002'
      LOG_LEVEL: 'LOG_DEBUG'
      WRITE_TIMEOUT: '1800'
      WRITE_JITTER:  '1800'
      WRITE_THREADS: '4'
      FLUSH_DEAD_DATA_INTERVAL: '3600'
    stdin_open: true
    volumes:
     - type: volume
       source: "librenms_db_volume"
       target: "/data/db"
       volume:
         nocopy: true
     - type: volume
       source: "librenms_journal_volume"
       target: "/data/journal"
       volume:
         nocopy: true
    tty: true
    networks:
      - librenms
```

Volumes are NFS volumes therefore permission fixing is not working and run every time the container starts.

### Docker info

```
Containers: 30
 Running: 9
 Paused: 0
 Stopped: 21
Images: 22
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: cifs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: c23kzsaue43y9mu1wto5cuebc
 Is Manager: false
 Node Address: 10.x.y.z
 Manager Addresses:
  172.x.y.z:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.52-2.ph3-esx
Operating System: VMware Photon OS/Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.818GiB
Name: ncc-2010
ID: IPMX:HP6D:SBCX:ABTR:LITL:7GTG:D5OU:GV6M:N3UL:3RVH:TU4N:6GBW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Logs

```    
Setting timezone to UTC...
Checking if rrdcached UID / GID has changed...
```

### Notes
I guess a potential fix would be to use a (configurable?) `--start-period=` setting of at least a few minutes (`180s` to `300s`). If the startup is quicker, the healthcheck will succeed quicker as well, if it's taking that long, it won't kick in until the bootstrap has finished.

With version `1.7.0`, the container starts properly, the main difference to `1.7.2` I could spot was the health check that was introduced.
