### ISSUE TITLE
rrdcached healtcheck fails at journal replay on startup

### ISSUE THREAD

**Issue by timerealm** [crazy-max/docker-rrdcached#8]
#### Steps to reproduce this issue

1. Deploy rrdcached with a journal file. Using "nc 172.1.1.1 42217" and s"stats" command inside of the container verify that the journal is being filled.
2. Update swarm service to trigger container reload for rrdcached service
3. watch for the rrdcached logs as the containers fails repeatably until removing the journal file

#### Expected behaviour

> Container start up normally and serve clients

#### Actual behaviour

Container starts up finds journal file, start replaying journal and in 10 seconds it gets killed due to the healthcheck failure:
HEALTHCHECK --interval=10s --timeout=5s \
  CMD echo PING | nc 127.0.0.1 42217 | grep PONG || exit 1

The service does not return pong until journal reply is completed, but this takes longer that 10s.

Ends up in a loop until I delete the journal file.

Log:
checking for journal files,
replaying from journal: /data/journal/rrd.journal.1596546311.329723,
caught SIGTERM

### Configuration

* Docker version (type `docker --version`) :
Docker version 19.03.12, build 48a66213fe

* Docker compose version if applicable (type `docker-compose --version`) : 
Used docker swarm deploy
* Platform (Debian 9, Ubuntu 18.04, ...) : 
Debian 10 and Ubuntu 20 LTS
* System info (type `uname -a`) : 
Linux vit-net-r-dock01 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```yaml
    rrdcached:
        image: crazymax/rrdcached
        #container_name: rrdcached
        volumes:
          - type: bind
            source: /storage/libre-docker/librenms/librenms_data/librenms/rrd
            target: /data/db
          - type: bind
            source: /storage/libre-docker/librenms/librenms_data/librenms/rrd-journal
            target: /data/journal
        networks:
         - prod_int_net
        deploy:
         placement:
            constraints:
             - "node.labels.placement == dc"
         mode: replicated
         replicas: 1
        restart: always
        environment:
         << : *env-global        
         LOG_LEVEL: "LOG_INFO"
         WRITE_TIMEOUT: "600"
         WRITE_JITTER: "1800"
         WRITE_THREADS: "4"
         FLUSH_DEAD_DATA_INTERVAL: "3600"
```

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```
Creating configuration...
Fixing perms...
starting up
ecking for journal files
replaying from journal: /data/journal/rrd.journal.1596547408.731787
caught SIGTERM

**Comment by crazy-max** [comment]
@rigocalin I have added the [start-period](https://docs.docker.com/engine/reference/builder/#healthcheck) parameter. If the value is still too low you can [override its value](https://docs.docker.com/compose/compose-file/#healthcheck) in your composition:

```yaml
    rrdcached:
        image: crazymax/rrdcached
        #container_name: rrdcached
        volumes:
          - type: bind
            source: /storage/libre-docker/librenms/librenms_data/librenms/rrd
            target: /data/db
          - type: bind
            source: /storage/libre-docker/librenms/librenms_data/librenms/rrd-journal
            target: /data/journal
        networks:
         - prod_int_net
        healthcheck:
          start_period: 10m
        deploy:
         placement:
            constraints:
             - "node.labels.placement == dc"
         mode: replicated
         replicas: 1
        restart: always
        environment:
         << : *env-global        
         LOG_LEVEL: "LOG_INFO"
         WRITE_TIMEOUT: "600"
         WRITE_JITTER: "1800"
         WRITE_THREADS: "4"
         FLUSH_DEAD_DATA_INTERVAL: "3600"
```
